name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push images
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=danielcgwright/portfolio
          TIMESTAMP_TAG=$(date +%s)

          # Build image with timestamp tag
          docker build . -f Dockerfile -t $IMAGE_NAME:$TIMESTAMP_TAG -t $IMAGE_NAME:latest

          # Push both tags
          docker push $IMAGE_NAME:$TIMESTAMP_TAG
          docker push $IMAGE_NAME:latest
